Libraries Used

In [2]:
from scipy.cluster.vq import kmeans,whiten,vq
import numpy as np
import sklearn
from sklearn import preprocessing, cross_validation, neighbors
import pandas as pd


C:\Users\jithi\Anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


Reading datasets

In [4]:
a=pd.read_csv(r"H:\my works pros\projects\abcd cardata.csv")
b=pd.read_csv(r"H:\my works pros\projects\myproject tr.csv")
b

Traffic Volume Count Location  Address                       Street  \
0                                1708 West                  71st Street   
1                                1275 West                  71st Street   
2                                 920 West                  71st Street   
3                                 758 West                  71st Street   
4                                 240 East                      71st St   
5                                2050 East                      71st St   
6                               8539 South               Commercial Ave   
7                               8933 South               Commercial Ave   
8                               9379 South               Commercial Ave   
9                               9730 South               Commercial Ave   
10                              4107 South            Cottage Grove Ave   
11                              4750 South            Cottage Grove Ave   
12                              5325 South            Cottage Grove Ave   
13                              6144 South            Cottage Grove Ave   
14                              6533 South            Cottage Grove Ave   
15                              6820 South            Cottage Grove Ave   
16                              7346 South            Cottage Grove Ave   
17                              8800 South            Cottage Grove Ave   
18                             10101 South            Cottage Grove Ave   
19                              1603 South                    Damen Ave   
20                              1959 South                    Damen Ave   
21                              2259 South                    Damen Ave   
22                              2566 South                    Damen Ave   
23                              3460 South                    Damen Ave   
24                              3630 South                    Damen Ave   
25                              4936 South                    Damen Ave   
26                              5929 South                    Damen Ave   
27                              6755 South                    Damen Ave   
28                              7509 South                    Damen Ave   
29                              3030 South  Dr Martin Luther King Jr Dr   
..                                     ...                          ...   
182                              2108 West                  95th Street   
183                              1850 West                  95th Street   
184                              1222 West                  95th Street   
185                               948 West                  95th Street   
186                               305 West                  95th Street   
187                               202 West                  95th Street   
188                               206 East                  95th Street   
189                              1057 East                  95th Street   
190                              2097 East                  95th Street   
191                              3502 East                  95th Street   
192                               537 West                 103rd Street   
193                               112 West                 103rd Street   
194                               235 East                     103rd St   
195                               907 East                     103rd St   
196                             7141 South                  Chicago Ave   
197                              2230 West                Garfield Blvd   
198                              1848 West                Garfield Blvd   
199                               226 East                Garfield Blvd   
200                               120 West                Garfield Blvd   
201                             1359 South                    Loomis St   
202                             1905 South                    Loomis St   
203                          

create 'first' list to store latitude,longitudde details 

In [4]:

first=b[['Latitude','Longitude']]
#first

Created odf flag to know whether the rider is  already in a ride or not & c is assigned with first list values

In [5]:
odf=np.array(a['on duty flag'])
c=np.array(first)

# Label Encoding

encodeing 'street' into int values to fit

In [6]:

en=preprocessing.LabelEncoder()
b['Street']=en.fit_transform(b['Street'])
seconds=np.array(b['Street'])
a['Street']=en.fit_transform(a['Street'])
seconda=np.array(a['Street'])
seconda

array([ 7,  7,  7,  7,  6,  6, 27, 27, 27, 27, 28, 28, 28, 28, 28, 28, 28,
       28, 28, 29, 29, 29, 29, 29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30,
       30, 30, 31, 31, 35, 35, 35, 35, 35, 36, 38, 38, 38, 38, 38, 38, 37,
       30, 30, 39, 43, 43, 43, 43, 43, 43, 43, 43, 45, 45, 45, 46, 46, 46,
       46, 46, 46, 46, 46, 46, 49, 49, 49, 21, 21, 21, 21, 21, 22, 22, 22,
       22, 22, 22, 22, 22, 22, 26, 26, 26, 26, 26, 33, 33, 33, 33, 33, 33,
       33, 33, 33, 48, 48, 48, 48, 48, 50, 50, 50, 50, 50, 50, 50, 50, 50,
       50, 51, 47, 47, 47, 47, 47, 47, 47, 18, 18, 20, 20,  0,  0, 23, 23,
       24, 40, 34, 42, 52,  4,  4,  3,  3,  5,  5,  5,  9,  8,  8,  8, 11,
       11, 10, 10, 10, 13, 13, 13, 13, 12, 12, 12, 12, 15, 16, 14, 15, 15,
       15, 15, 14, 17, 17, 17, 17, 17, 17, 17, 17, 17, 19, 19, 19, 19, 19,
       19, 19, 19, 19, 19,  2,  2,  1,  1, 25, 32, 32, 32, 32, 41, 41, 41,
       41, 41, 41, 41, 41, 44, 44, 44], dtype=int64)

# K-means clustering

clustering 'streets' using k-means clustering

In [7]:

centroids,v=kmeans(c,8)
classi,vc=vq(c,centroids)
classi

array([3, 3, 3, 3, 7, 4, 0, 0, 0, 0, 6, 6, 7, 7, 7, 7, 7, 5, 5, 2, 2, 2,
       2, 2, 2, 3, 3, 3, 3, 6, 6, 6, 7, 7, 5, 5, 4, 0, 6, 6, 6, 6, 7, 0,
       4, 4, 4, 4, 5, 4, 5, 7, 6, 4, 6, 6, 6, 6, 6, 6, 7, 5, 4, 4, 4, 6,
       6, 6, 7, 7, 7, 7, 5, 5, 6, 7, 1, 2, 6, 2, 6, 2, 2, 2, 2, 3, 3, 3,
       3, 1, 1, 6, 6, 6, 6, 6, 2, 2, 6, 3, 3, 3, 3, 1, 1, 7, 1, 1, 1, 1,
       2, 2, 2, 2, 3, 3, 3, 1, 1, 1, 3, 5, 4, 5, 5, 5, 4, 4, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 4, 3, 3, 7, 7, 7, 4, 4, 7, 7, 7, 4, 3, 7,
       7, 7, 4, 3, 3, 3, 7, 7, 7, 7, 4, 1, 1, 7, 5, 5, 5, 0, 0, 1, 1, 1,
       1, 1, 5, 5, 0, 0, 1, 1, 1, 1, 1, 1, 5, 5, 0, 0, 1, 1, 5, 5, 7, 3,
       3, 7, 7, 2, 2, 3, 3, 3, 3, 3, 1, 2, 2, 2])

Created Rider-array to store assigned driver details


In [8]:
rider_array=np.array(a[['Make','Model','Mileage (kmpl)','Seating capacity','Car class (personal opinion)','Registration number']])
rider_array

array([['Chevrolet', 'Aveo [2006-2009]1.4', 11.9, 5, 'Small car',
        'KL-07-A-7252'],
       ['Chevrolet', 'Aveo [2006-2009]LS 1.4', 11.9, 5, 'Small car',
        'KL-07-A-5078'],
       ['Chevrolet', 'Aveo [2006-2009]LS 1.4 Ltd', 11.9, 5, 'Small car',
        'KL-07-A-7270'],
       ...,
       ['Chevrolet', 'TaveraNY Elite SS - D1 - BS II', 11.6, 8,
        'Compact SUV', 'KL-07-A-6227'],
       ['Chevrolet', 'TaveraNY Elite SS - D1 - BS III', 11.6, 8,
        'Compact SUV', 'KL-07-A-9113'],
       ['Chevrolet', 'TrailblazerLTZ AT', 11.45, 7, 'Large SUV',
        'KL-07-A-7835']], dtype=object)

K-means Cluster is added to the datasets as 'Clouster Code'

In [9]:
a['Clouster code']=classi
a
b['Clouster code']=classi
b


Traffic Volume Count Location  Address  Street   Latitude  Longitude  \
0                                1708 West       7  41.764877 -87.666635   
1                                1275 West       7  41.765008 -87.657067   
2                                 920 West       7  41.765153 -87.647751   
3                                 758 West       7  41.765204 -87.644371   
4                                 240 East       6  41.765644 -87.618476   
5                                2050 East       6  41.766260 -87.574226   
6                               8539 South      27  41.739836 -87.551476   
7                               8933 South      27  41.732725 -87.551320   
8                               9379 South      27  41.724444 -87.551124   
9                               9730 South      27  41.718183 -87.551016   
10                              4107 South      28  41.820171 -87.606798   
11                              4750 South      28  41.807987 -87.606532   
12                              5325 South      28  41.797881 -87.606302   
13                              6144 South      28  41.782690 -87.605979   
14                              6533 South      28  41.775779 -87.605826   
15                              6820 South      28  41.770685 -87.605711   
16                              7346 South      28  41.760801 -87.605452   
17                              8800 South      28  41.734791 -87.604779   
18                             10101 South      28  41.710922 -87.605730   
19                              1603 South      29  41.859378 -87.676043   
20                              1959 South      29  41.854926 -87.675920   
21                              2259 South      29  41.850395 -87.675790   
22                              2566 South      29  41.844875 -87.675652   
23                              3460 South      29  41.830389 -87.675279   
24                              3630 South      29  41.827625 -87.675208   
25                              4936 South      29  41.803741 -87.674569   
26                              5929 South      29  41.785746 -87.674075   
27                              6755 South      29  41.770409 -87.673671   
28                              7509 South      29  41.757363 -87.673336   
29                              3030 South      30  41.838419 -87.617465   
..                                     ...     ...        ...        ...   
182                              2108 West      19  41.721037 -87.675323   
183                              1850 West      19  41.721119 -87.669564   
184                              1222 West      19  41.721324 -87.653942   
185                               948 West      19  41.721409 -87.647429   
186                               305 West      19  41.721622 -87.631298   
187                               202 West      19  41.721659 -87.628777   
188                               206 East      19  41.721813 -87.618662   
189                              1057 East      19  41.722153 -87.597339   
190                              2097 East      19  41.722499 -87.572943   
191                              3502 East      19  41.722916 -87.538794   
192                               537 West       2  41.706991 -87.636980   
193                               112 West       2  41.707125 -87.626548   
194                               235 East       1  41.707260 -87.617296   
195                               907 East       1  41.707533 -87.600985   
196                             7141 South      25  41.764998 -87.604360   
197                              2230 West      32  41.793839 -87.681286   
198                              1848 West      32  41.793942 -87.671875   
199                               226 East      32  41.794746 -87.619558   
200                               120 West      32  41.794582 -87.629567   
201                             1359 South      41  41.863965 -87.661484   
202                             1905 South      41  

# finding nearest neighbour using knn

created secondary fit variable 'secondry' to store cluster-centroid values

In [10]:
secondry=np.array(b['Clouster code'])

cross-validation first vs secondry

In [18]:
x_train,x_test,z_train,z_test=cross_validation.train_test_split(first,secondry,test_size=0.2)
z_test

array([3, 0, 7, 3, 6, 5, 7, 4, 6, 0, 6, 1, 7, 6, 3, 6, 0, 6, 7, 0, 2, 6,
       5, 4, 7, 2, 7, 3, 1, 1, 5, 6, 4, 7, 4, 3, 5, 3, 5, 4, 3, 3, 4])

fitting(classification)

In [11]:
clf=neighbors.KNeighborsClassifier()
clf.fit(x_train,z_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

finding max accuracy

In [12]:
acry=clf.score(x_test,z_test)
acry


0.9302325581395349

# Getting lattitude,longitude details from user

In [14]:
la=input("enter your lattitude?")
lo=input("enter your longittude?")
de=int(input("enter you destination code(1/26):"))
typ=input("enter \n1.p-d go\n2.p-d pool\n3.p-d premier")
#enter your longittude?41.764877  --87.666635

enter your lattitude?41.864029
enter your longittude?-87.656597
enter you destination code(1/26):16


Knn location prediction to find a ride

In [16]:
g=np.array([la,lo]).reshape(1,-1)
locati=clf.predict(g)
locati[0]

3

finding a ride

In [1]:
des=np.array(a['destination'])
des
xn=classi.size
for i in range(xn):
    if(locati[0]==classi[i]):
        
        if(des[i]==de):
          
            if(odf[i]==0):
                print("from:{}".format(locati[0]))
                print("to.:{}".format(des[i]))
                print("ride found")
                print("rider details\n.{}".format(rider_array[i]))
                break
            
            
        

NameError: name 'np' is not defined

array([2, 2, 2, 2, 6, 7, 1, 1, 1, 1, 3, 3, 6, 6, 6, 6, 6, 0, 0, 5, 5, 5,
       5, 5, 5, 2, 2, 2, 2, 3, 3, 3, 6, 6, 0, 0, 7, 1, 3, 3, 3, 3, 6, 1,
       7, 7, 7, 7, 7, 7, 1, 6, 3, 7, 3, 3, 3, 3, 3, 3, 6, 0, 7, 7, 7, 3,
       3, 3, 6, 6, 6, 0, 0, 0, 3, 6, 0, 5, 3, 5, 3, 5, 5, 5, 5, 2, 2, 2,
       2, 4, 4, 3, 3, 3, 3, 3, 5, 5, 3, 2, 2, 2, 2, 4, 4, 6, 4, 4, 4, 4,
       5, 5, 5, 5, 2, 2, 2, 4, 4, 4, 2, 1, 7, 7, 1, 7, 7, 7, 1, 1, 4, 4,
       1, 1, 1, 1, 4, 4, 1, 1, 7, 2, 2, 6, 6, 6, 7, 7, 6, 6, 6, 7, 2, 2,
       6, 6, 7, 2, 2, 2, 6, 6, 6, 6, 7, 4, 4, 0, 0, 7, 7, 1, 1, 4, 4, 4,
       0, 0, 0, 0, 7, 1, 4, 4, 4, 4, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 6, 2,
       2, 6, 6, 5, 5, 2, 2, 2, 2, 2, 4, 5, 5, 5])

array([['Chevrolet', 'Aveo [2006-2009]1.4', 11.9, 5, 'Small car',
        'KL-07-A-7252'],
       ['Chevrolet', 'Aveo [2006-2009]LS 1.4', 11.9, 5, 'Small car',
        'KL-07-A-5078'],
       ['Chevrolet', 'Aveo [2006-2009]LS 1.4 Ltd', 11.9, 5, 'Small car',
        'KL-07-A-7270'],
       ...,
       ['Chevrolet', 'TaveraNY Elite SS - D1 - BS II', 11.6, 8,
        'Compact SUV', 'KL-07-A-6227'],
       ['Chevrolet', 'TaveraNY Elite SS - D1 - BS III', 11.6, 8,
        'Compact SUV', 'KL-07-A-9113'],
       ['Chevrolet', 'TrailblazerLTZ AT', 11.45, 7, 'Large SUV',
        'KL-07-A-7835']], dtype=object)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

0.9534883720930233

enter your lattitude?41.764877
enter your longittude?-87.666635
enter you destination code(1/26):11


array([2])

failed
failed
failed
failed
oh
oh
failed
failed
failed
failed
failed
failed
oh
oh
oh
oh
oh
failed
failed
oh
oh
oh
oh
oh
oh
failed
failed
failed
failed
failed
failed
failed
oh
oh
failed
failed
oh
failed
failed
failed
failed
failed
oh
failed
oh
oh
oh
oh
oh
oh
failed
oh
failed
oh
failed
failed
failed
failed
failed
failed
oh
failed
oh
oh
oh
failed
failed
failed
oh
oh
oh
failed
failed
failed
failed
oh
failed
oh
failed
oh
failed
oh
oh
oh
oh
failed
failed
failed
failed
oh
oh
failed
failed
failed
failed
failed
oh
oh
failed
failed
failed
failed
failed
oh
oh
oh
oh
oh
oh
oh
oh
oh
oh
oh
failed
failed
failed
oh
oh
oh
failed
failed
oh
oh
failed
oh
oh
oh
failed
failed
oh
oh
failed
failed
failed
failed
oh
oh
failed
failed
oh
failed
failed
oh
oh
oh
oh
oh
oh
oh
oh
oh
failed
failed
oh
oh
oh
failed
failed
failed
oh
oh
oh
oh
oh
oh
oh
failed
failed
oh
oh
failed
failed
oh
oh
oh
failed
failed
failed
failed
oh
failed
oh
oh
oh
oh
failed
failed
failed
failed
failed
failed
failed
failed
failed
failed
oh
failed
fa